login:
    pattern: /login
    defaults: { _controller: AreYouStillThereBundle:Security:login }

login_check:
    pattern: /login_check

AreYouStillThereBundle:
    resource: "@AreYouStillThereBundle/Resources/config/routing.yml"
    prefix:   /
