hearbeat:
    pattern:  /heartbeat
    defaults: { _controller: AreYouStillThereBundle:Heartbeat:index }

send_heartbeat:
    pattern:  /heartbeat/send
    defaults: { _controller: AreYouStillThereBundle:Heartbeat:send }
    requirements: { _method: POST }
