parameters:
#    are_you_still_there.example.class: AreYou\StillThereBundle\Example

services:
#    are_you_still_there.example:
#        class: %are_you_still_there.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    are_you_still_there.user_provider:
        parent: doctrine.odm.mongodb.security.user.provider
        public: true
        arguments:
            - AreYou\StillThereBundle\Document\User
            - username
