parameters:
    are_you_still_there.mail.from: 'no-reply@areyoustillthe.re'

services:
#    are_you_still_there.example:
#        class: %are_you_still_there.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    are_you_still_there.user_provider:
        parent: doctrine.odm.mongodb.security.user.provider
        public: true
        arguments:
            - AreYou\StillThereBundle\Document\User
            - username

    are_you_still_there.heartbeat_listener:
        class: AreYou\StillThereBundle\Listener\HeartbeatListener
        arguments:
            - @are_you_still_there.heartbeat_sender
        tags:
            - { name: doctrine.odm.mongodb.default_event_subscriber }

    are_you_still_there.heartbeat_sender:
        class: AreYou\StillThereBundle\Sender\HeartbeatSender
        arguments:
            - %are_you_still_there.mail.from%
            - @service_container
