parameters:
    are_you_still_there.heartbeat_sender.from: 'no-reply@areyoustillthe.re'
    are_you_still_there.heartbeat_zmq.url: 'tcp://127.0.0.1:5555'

services:
    are_you_still_there.user_provider:
        parent: doctrine.odm.mongodb.security.user.provider
        public: true
        arguments:
            - AreYou\StillThereBundle\Document\User
            - username

    are_you_still_there.heartbeat_listener:
        class: AreYou\StillThereBundle\Listener\HeartbeatListener
        arguments:
            - @are_you_still_there.heartbeat_sender
            - @are_you_still_there.heartbeat_zmq
        tags:
            - { name: doctrine.odm.mongodb.default_event_subscriber }

    are_you_still_there.heartbeat_sender:
        class: AreYou\StillThereBundle\Sender\HeartbeatSender
        arguments:
            - %are_you_still_there.heartbeat_sender.from%
            - @service_container

    are_you_still_there.heartbeat_zmq:
        class: AreYou\StillThereBundle\ZMQ\HeartbeatZmq
        arguments:
            - %are_you_still_there.heartbeat_zmq.url%
